-- Adminer 4.7.7 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `cars`;
CREATE TABLE `cars` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `model` varchar(25) NOT NULL,
  `brand` varchar(25) NOT NULL,
  `released_year` int(11) NOT NULL,
  `imageURL` varchar(10000) NOT NULL,
  `description` varchar(10000) NOT NULL,
  `mileage` int(11) NOT NULL,
  `price` int(11) NOT NULL,
  `color` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `cars` (`id`, `model`, `brand`, `released_year`, `imageURL`, `description`, `mileage`, `price`, `color`) VALUES
(1,	'Highlander ',	'Toyota ',	2022,	'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Toyota_Highlander_Hybrid_%28XU70%29_1X7A6356.jpg/800px-Toyota_Highlander_Hybrid_%28XU70%29_1X7A6356.jpg',	'Vendez une Toyota Highlander 2022 avec seulement 15 000 km au compteur. Cette SUV offre un espace généreux pour sept passagers, avec une troisième rangée de sièges et un grand coffre pour toutes vos aventures familiales. Équipée de technologies de sécurité avancées, y compris la surveillance des angles morts et l\'assistance au maintien de la trajectoire. Intérieur en cuir, toit ouvrant et système multimédia de dernière génération. Parfait état, entretiens réguliers chez le concessionnaire avec historique complet. Un véhicule fiable et élégant pour la sécurité et le confort de votre famille!',	150000,	45000,	2),
(2,	'Corvette ',	'Chevrolet ',	2020,	'https://cdn.motor1.com/images/mgl/P1j3K/s1/2020-chevrolet-corvette-first-drive.jpg',	'À vendre, Chevrolet Corvette 2020, un vrai bijou avec seulement 10 000 km. Cette voiture de sport légendaire est propulsée par un moteur V8 de 6.2L, garantissant des performances époustouflantes avec une accélération de 0 à 100 km/h en moins de 4 secondes. Design extérieur rouge flamboyant avec intérieur en cuir noir, équipée de jantes en alliage 19 pouces, système de navigation et pack audio haut de gamme. Excellent état, toujours garée en garage, non-fumeur. Une opportunité rare de posséder un véhicule qui fait tourner toutes les têtes.',	95000,	64990,	0),
(3,	'307',	'Peugeot',	2007,	'https://upload.wikimedia.org/wikipedia/commons/3/37/2020_-Peugeot_308_II%28B%29_-_55.jpg',	'Peugeot Très sympa',	150000,	5000,	0),
(4,	'Civic ',	'Honda ',	2019,	'https://www.carscoops.com/wp-content/uploads/2020/07/Honda-Civic-Type-R-7-1024x555.jpg',	'Mettez la main sur une Honda Civic 2019, seulement 30 000 km, une voiture compacte idéale pour la ville. Reconnue pour sa fiabilité et son économie de carburant, cette Civic est équipée d\'un moteur 1.8L économique mais réactif. Carrosserie en bleu métallique avec intérieur en tissu bien entretenu, système d\'info-divertissement avec connectivité Bluetooth et caméra de recul. Parfait état mécanique, entretiens à jour. Un choix excellent pour ceux qui cherchent un véhicule abordable mais de qualité.',	5000,	47000,	3),
(5,	'Classe S',	'Mercedes-Benz',	2021,	'https://images.caradisiac.com/images/7/9/4/4/187944/S1-essai-mercedes-classe-s-2021-le-futur-est-aujourd-hui-661123.jpg',	'A la vente une Mercedes-Benz S-Class 2021, 12 000 km, le summum du luxe automobile. Avec son design intérieur opulent incluant des sièges en cuir massant, un système de sonorisation Burmester 3D, et une ambiance lumineuse ajustable, cette voiture ne laisse rien au hasard. Motorisation puissante avec un V8 biturbo, cette berline offre confort et performance. Couleur extérieure noire obsidienne et finitions de haute qualité. Entretenue exclusivement chez le concessionnaire Mercedes, avec garantie prolongée disponible. Pour ceux qui exigent le meilleur dans chaque aspect de leur véhicule.',	12000,	95000,	2),
(6,	'Golf 7',	'Volkswagen ',	2014,	'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/2013_Volkswagen_Golf_SE_BlueMotion_Technology_1.4_Front.jpg/2560px-2013_Volkswagen_Golf_SE_BlueMotion_Technology_1.4_Front.jpg',	'À vendre, Volkswagen Golf 7 1.6 TDI 110 FAP BlueMotion, année modèle 2016, motorisation 1.6 TDI 110 FAP BlueMotion, couleur grise. Avec seulement 75,000 km, cette Golf combine parfaitement économie de carburant et performances. Equipée de la technologie BlueMotion pour une efficacité maximale, elle offre également un confort de conduite supérieur avec des sièges ergonomiques, climatisation automatique, et système de navigation intégré. Parfaitement entretenue, carnet d\'entretien complet disponible. Un choix idéal pour ceux qui recherchent une voiture fiable et économique avec une touche d\'élégance européenne.',	158000,	9900,	2),
(7,	'307 SW',	'Peugeot ',	2007,	'https://upload.wikimedia.org/wikipedia/commons/4/42/Peugeot_307_SW_front.jpg',	' Peugeot 307 SW - Parfaite pour la Famille, Très Bon État! Offrez-vous cette Peugeot 307 SW 1.6 HDI 110 FAP, une voiture familiale spacieuse et versatile, idéale pour tous vos besoins quotidiens. Mise en circulation en 2008 et affichant 120,000 km au compteur. Ce modèle bénéficie d\'un intérieur bien agencé avec beaucoup d\'espace de rangement et un grand coffre, parfait pour les longs voyages ou les courses familiales. Équipée de barres de toit, climatisation, et d\'un système audio de qualité. Tous les entretiens sont à jour. Une voiture familiale fiable à un prix attractif.',	250000,	4000,	NULL),
(8,	'Série 4 Gran Coupé',	'BMW ',	2014,	'https://cloud.leparking.fr/2021/11/03/22/17/bmw-serie-4-gran-coupe-bmw-serie-4-428i-gran-coupe-245ch-luxury-bva8-f36-marron_8323803326.jpg',	'Découvrez cette magnifique BMW Série 4 Gran Coupé F36 de 2014, une fusion parfaite d\'élégance et de dynamisme. Avec seulement 65,000 km, cette berline sportive est peinte en noir métallisé et propulsée par un moteur puissant garantissant des performances exceptionnelles. Son intérieur luxueux inclut des sièges en cuir, un système de navigation avancé, et un toit ouvrant panoramique pour une expérience de conduite inégalée. Bien entretenue avec un historique de service complet, cette BMW est prête à offrir le style et la sophistication que vous méritez.  Chacune de ces annonces met en avant les attributs clés du véhicule, tout en assurant une description engageante qui vise à susciter l\'intérêt des acheteurs potentiels et à mettre en confiance sur l\'état et la qualité du véhicule.',	65000,	35000,	NULL),
(9,	' Série 1 116i ',	'BMW ',	2016,	'https://www.ora7.fr/occasions-bmw/montelimar/40380/photo/hd/bmw-serie-1-noir-1.jpg',	'Proposez à la vente cette exceptionnelle BMW Série 1 116i de 2016, phase 2, finition noire brillante. Avec seulement 50,000 km au compteur, ce modèle est un parfait mélange de style, de confort et de dynamisme, adapté aussi bien à la conduite urbaine qu\'aux longues distances.  Sous le capot, vous trouverez un moteur essence efficient de 1.6 litre, connu pour sa fiabilité et son économie de carburant, tout en offrant une expérience de conduite exaltante. L\'intérieur est équipé de sièges en tissu premium, d\'un système d\'infodivertissement complet avec Bluetooth et navigation GPS, et d\'un volant multifonction pour une maîtrise totale sans quitter les yeux de la route.  Cette BMW est également dotée de jantes en alliage léger, d\'une transmission manuelle à six vitesses et d\'une série de systèmes d\'assistance à la conduite, incluant le contrôle dynamique de la stabilité (DSC) et le contrôle de traction dynamique (DTC). La voiture a été méticuleusement entretenue avec tous les services à jour, assurant une tranquillité d\'esprit complète pour le futur propriétaire.  Ne ratez pas l\'opportunité de conduire cette sublime BMW Série 1, qui combine élégance noire et performances impressionnantes pour une expérience de conduite inoubliable. Voiture non-fumeur, vendue par le premier propriétaire. Contactez-nous pour une visite ou pour plus d\'informations.',	50000,	17000,	NULL),
(33,	'307',	'Peugeot',	2007,	'https://www.ora7.fr/occasions-bmw/montelimar/40380/photo/hd/bmw-serie-1-noir-1.jpg',	'Peugeot Très sympa',	150000,	5000,	0);

-- 2024-05-13 23:01:35
